import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'sonner'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        <div className="min-h-screen overflow-hidden items-center content-center bg-[#F9FAFB]">
          {children}
        </div>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
